"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.css";
const inter = Inter({ subsets: ['latin'] })
import Page from "./pagesdetails/Navbar";
import App from './enquiry-us/footer';
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import Button from 'react-bootstrap/Button';
//import "./enquiry-us/footer.css";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.min.css"
export const metadata = {
  title: 'My Forth App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Page/>
      
      {children}
        <App/>
        <footer/>
        </body>
    </html>
  )
}
